# Nombre (Integracion Continua)
name: CI
on:
 #Cada vez que se ejecute un push
 push:
 workflow_dispatch:

# Se declaran jobs y steps (jobs --< steps)
jobs:
  
 build:   
  runs-on: ubuntu-latest  
  steps:   
   - uses: actions/checkout@v3   
   - name: Start
     run: |
       echo "Hola, comienzo de tarea final"

 #integracion con SonarCloud 
 SAST:
  runs-on: ubuntu-latest
  needs: build  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
 
  - name: Setup Node.js
    uses: actions/checkout@v3
    with:
      node-version: '14'
 
  - name: Install dependencies
    run: npm install
 
  - name: Run SonarCloud analysis
    uses: sonarsource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
