# Nombre (Integracion Continua)
name: CI
on:
 push:
 workflow_dispatch:

jobs:

 #Job 1.0 - Build
 build:   
  runs-on: ubuntu-latest  
  #step 1 - Saludo
  steps:   
   - uses: actions/checkout@v3   
   - name: Comienzo
     run: |
       echo "Hola, comienzo de tarea final"

   #step 2 - Login con Docker
   - name: Docker Login
     uses: docker/login-action@v3.0.0
     with:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_PASS }}

   #step 3 - Img con Docker
   - name: Docker Build 
     run: |
      docker build --tag setocl/final-lab:latest .
     working-directory: ${{ github.workspace }}
 
 #Job 2.0 - Integracion con SonarCloud 
 SAST:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
 
  - name: Setup Node.js
    uses: actions/checkout@v3
    with:
      node-version: '14'
 
  - name: Install dependencies
    run: npm install
  
  - name: Run SonarCloud analysis
    uses: sonarsource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#Job 3.0 - Analisis SCA con Dependency Check
 SCA:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '14'

  - name: Install Dependencies
    run: npm install
  
  - name: Run Dependency Check
    uses: dependency-check/Dependency-Check_Action@1.1.0
    with:
      project: 'final-lab'
      path: '.'
      format: 'HTML'

  - name: Upload Dependency Check Report
    uses: actions/upload-artifact@master
    with:
      name: dependency-check-report
      path: ${{github.workspace}}/reports

          


#Job 3.1 - Analisis GHAS
# GHAS:
#  runs-on: ubuntu-latest
#  needs: build
#  steps:
#  - name: Checkout code
#    uses: actions/checkout@v3

#  - name: Install dependencies
#    run: npm install
    
#  - name: Software Composition Analysis with GHAS
#    run: npm audit --json > npm_audit_report.json
#    shell: bash


