# Nombre (Integracion Continua)
name: CI
on:
 push:
 workflow_dispatch:

jobs:

 #Job 01 - Saludo incial
 build:   
  runs-on: ubuntu-latest  
  steps:   
   - uses: actions/checkout@v3   
   - name: Start
     run: |
       echo "Hola, comienzo de tarea final"

 
 #Job 02 - Integracion con SonarCloud 
 SAST:
  runs-on: ubuntu-latest
  needs: build  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
 
  - name: Setup Node.js
    uses: actions/checkout@v3
    with:
      node-version: '14'
 
  - name: Install dependencies
    run: npm install
  
  - name: Run SonarCloud analysis
    uses: sonarsource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#Job 03 - Analisis SCA con Dependency Check
 SCA:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '14'

  - name: Install Dependencies
    run: npm install

  - name: Run Dependency Check
    run: |
      npm install -g dependency-check
      dependency-check --project . --format HTML --output dependency-check-report.html

  - name: Upload Dependency Check Report
    uses: actions/upload-artifact@v2
    with:
      name: dependency-check-report
      path: dependency-check-report.html

